### ISSUE TITLE
Error: unknown device ID

### ISSUE THREAD

**Issue by Tjaden** [Ryex/ic10emu#20]
![image](https://github.com/Ryex/ic10emu/assets/4202880/9f9d160c-6b96-4105-bfce-952dff3a615b)
**Error**
> Error in Virtual Machine Error
> ic encountered an error: Error on line 61: unknown device ID '4'

Device with id is present.

**Comment by Ryex** [comment]
What does line 61 try to do? it's not in your screenshot

**Comment by Tjaden** [comment]
That's a good question.
For me, the problem was in the line marked in purple.

curIdStacker was 4


Unfortunately, I can't reproduce this right now because the code no longer exists.

**Comment by Ryex** [comment]
well if you can reproduce it at  https://ryex.github.io/ic10emu/ let me know. (give it 15 minuets form the creation of this comment, I *just* merged)

**Comment by Tjaden** [comment]
Es tut mir leid, ich bekomme es nicht reproduziert.

ärgerlich
